// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd1VnX6HrfLAPEGZxNsDpeER0t7kS49iE',
    appId: '1:733158771272:web:316c4b7d625b48dac2667d',
    messagingSenderId: '733158771272',
    projectId: 'attendanceapp-df353',
    authDomain: 'attendanceapp-df353.firebaseapp.com',
    storageBucket: 'attendanceapp-df353.firebasestorage.app',
    measurementId: 'G-97TQ4CXLYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ6bKgPYII50q_z7Bxg8xCXWnZW6kqYGI',
    appId: '1:733158771272:android:f40a7a6a6a4e1375c2667d',
    messagingSenderId: '733158771272',
    projectId: 'attendanceapp-df353',
    storageBucket: 'attendanceapp-df353.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH5mw_icAsbNsABmTWjSGVVvLS1VzBhiE',
    appId: '1:733158771272:ios:f06c9b44f2e5fb7ac2667d',
    messagingSenderId: '733158771272',
    projectId: 'attendanceapp-df353',
    storageBucket: 'attendanceapp-df353.firebasestorage.app',
    iosBundleId: 'com.example.alexBankCoreTeamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH5mw_icAsbNsABmTWjSGVVvLS1VzBhiE',
    appId: '1:733158771272:ios:f06c9b44f2e5fb7ac2667d',
    messagingSenderId: '733158771272',
    projectId: 'attendanceapp-df353',
    storageBucket: 'attendanceapp-df353.firebasestorage.app',
    iosBundleId: 'com.example.alexBankCoreTeamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSa-i9fSWGV_elg6lXQO8mha5apuREMVg',
    appId: '1:733158771272:web:159adaee69452224c2667d',
    messagingSenderId: '733158771272',
    projectId: 'attendanceapp-df353',
    authDomain: 'attendanceapp-df353.firebaseapp.com',
    storageBucket: 'attendanceapp-df353.firebasestorage.app',
    measurementId: 'G-9WG4P49LEV',
  );
}
